# Generated by Django 5.1.7 on 2025-05-24 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fd', '0005_alter_product_image_order_orderitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличными'), ('card', 'Картой курьеру'), ('online', 'Онлайн оплата')], default='cash', max_length=20),
        ),
        migrations.AlterModelTable(
            name='order',
            table=None,
        ),
    ]
